syntax = "proto3";
option go_package = ".;protos";

import "expression-calculate.proto";

// requires(NONE)
message ExpressionOutputReq
{
    DataSourceParams request = 1;
}

message ExpressionOutputResp
{
    // We don't return the result here, that's a HTTP request to memoisation! We return
    // the key that the data is available with - and a job id if the data is not read yet,
    // because we may have had to trigger the expression to be calculated and that
    // will take time. If jobId is not blank, the client should listen for completed jobs
    // for that jobId. When the job is complete it can then query it from memoisation
    string key = 1;
    string jobId = 3;
}
