syntax = "proto3";
option go_package = ".;protos";

import "scan.proto";
import "roi.proto";


enum JobType
{
    JT_UNKNOWN = 0; // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
    JT_IMPORT_SCAN = 1;
    JT_REIMPORT_SCAN = 2;
    JT_IMPORT_IMAGE = 3;
    JT_RUN_QUANT = 4;
    JT_RUN_FIT = 5;
    JT_RUN_EXPRESSION = 6;
    JT_RUN_PYTHON_SCRIPT = 7;
    // TODO:
    // Future types:
    // JT_RUN_DIFFRACTION_DETECTOR, <-- to create the existing diffraction.db file, decouple from import
}

message JobStatus
{
    enum Status
    {
		UNKNOWN = 0; // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
        STARTING = 1;
        PREPARING_NODES = 2;
        RUNNING = 3;
        GATHERING_RESULTS = 4;
        COMPLETE = 5;
        ERROR = 6;
    }

    string jobId = 1; // @gotags: bson:"_id,omitempty"
    Status status = 2;
    string message = 3; // Optionally a message can be stored with the status
    string logId = 4; // The log ID - initially just AWS <log group name>_<log stream id>

    // What the job is operating on. Set depending on job type:
    // JT_IMPORT_SCAN => scan id
    // JT_IMPORT_IMAGE => image name
    // JT_RUN_QUANT => quant id
    string jobItemId = 10;


    JobType jobType = 11;

    uint32 startUnixTimeSec = 5; // Job start time
    uint32 lastUpdateUnixTimeSec = 6; // Job update time (if this changes, we send out an update)

    // Completion:
    uint32 endUnixTimeSec = 7; // Job completion time
    string outputFilePath = 8; // Where the job output its final result(s)
    repeated string otherLogFiles = 9; // Any other logs (eg PIQUANT log files) generated by the job

    // Job requestor
    string requestorUserId = 12; // Where the job output its final result(s)

    // Some more info about the job itself
    string name = 13; // Eg the quant, scan or image name
    repeated string elements = 14; // If it's a quant, the list of elements being quantified
}

enum NodeIndexMethod {
    NONE = 0;
	LOCAL = 1;
	REMOTE = 2;
	BOTH = 3;
}

message JobFilePath {
	// The remote file info
	string remoteBucket = 1;
	string remotePath = 2;

	// Local copy
	string localPath = 3;

    // Apply node index to this path (or not)
    // If this is false, we just use the path as is, but if
    // it's set to true, the local and remote paths have the
    // node number inserted in between the file name and its
    // extension. Eg node.pmcs becomes node00001.pmcs
    NodeIndexMethod applyNodeIndex = 4;
}

message JobConfig {
	// The job id
	string jobId = 1;

	// Logging method - If these are empty, we just log to stdout
	// LogCloudwatchGroup string
	// LogCloudwatchStream string

	// What files are required to be present when running the job?
	repeated JobFilePath requiredFiles = 2;

	// What command to execute
	string command = 3;
	repeated string args = 4;

	// What to upload on completion (if file doesn't exist, it can be ignored with a warning)
	repeated JobFilePath outputFiles = 5;

    // eg if this contains a 2, it means
    // we need to apply the node index to
    // Args[2] before running this job
    repeated int32 argIndexToApplyNodeIndexes = 6;
}

message ROIItemWithPMCs {
	repeated int32 pmcs = 1;
	ROIItem roiItem = 2;
}

message JobGroupConfig {
	string jobGroupId = 1; // @gotags: bson:"_id,omitempty"
	JobType jobType = 2; // Job type, mostly for annotation of job state
    string completionMethod = 3; // What to do when the job is completed, one of the JobComplete_* names
	string dockerImage = 4; // Docker image to run in each node
	bool fastStart = 5; // May go unused - but could be a way to run it locally on this machine if we know it's a quick job
	uint32 nodeCount = 6; // Node count, because NodeConfig can be asked to retrieve config of each node, but here we know the total
	JobConfig nodeConfig = 7;

	// Job meta-data - this contains task specific fields
	// TODO: Remove this or make it generic somehow! Perhaps move these to a json file that is saved with the job and expect it to be available at the end?
	// The problem is they are available at job creation, but also needed in the job completion task for certain jobs
	string associatedScanId = 8;   // Empty if none, or if it's across scans
	string jobName = 9;   // Optional job name, eg used for quants
	repeated string elementList = 10; // Optional element list, eg used for quants
	string requestorUserId = 11;
    string outputTitle = 12; // Optional, ends up in the title of an output file, eg the first row of a CSV
    bool combined = 13;
    bool quantByROI = 14;

    repeated ROIItemWithPMCs ROIs = 15;
	// Need configs for:
	// NodeOutputCombining - how to combine the outputs, eg PIQUANT map commands
	// Do we need to write overall job output/logs somewhere?
}


// Which API instance wants to handle this job? This is only used
// when it's an external request and APIs realise that an unknown
// job got completed. Now one will have to handle things like
// notification, so at that point all APIs will write their instance
// ID here, wait a little, then read it back. The API matching the
// written instance ID gets to do the job!
message JobHandlerDBItem {
    string id = 1; // @gotags: bson:"_id,omitempty"

    string jobId = 2;
    string handlerInstanceId = 3;
    uint32 timeStampUnixSec = 4;
}

// Individual jobs are written to the job queue. If a Job (above) involves multiple sub-jobs (eg PIQUANT run)
// then a single entry exists in the JobStatus table, but JobQueue will contain one for each sub-job. This way
// it can be individually run on a node (eg in a docker container on another machine) and accounted for when
// it completes/fails. Once all JobQueueItems for a given job group are complete, its completion code can run
// and it then gets removed from the job queue
message JobQueueItem
{
    string jobId = 1; // @gotags: bson:"_id,omitempty"

    // Include enough info to be able to start the job just using this structure! These form the
    // S3 path to the job, where the job param JSON should be waiting
    string jobGroupId = 2;
    string associatedScanId = 7;
    uint32 nodeIndex = 8;

    int64 createdTimeStampUnixSec = 3;
    int64 lastUpdatedTimeStampUnixSec = 4;

    enum State
    {
		UNKNOWN = 0; // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
        ASSIGNED = 1;
        RUNNING = 2;
        COMPLETE = 3;
        FAILED = 4;
    }

    State state = 5;
    string message = 6;
    string instanceId = 9;
    JobType jobType = 10;
}

message ScheduledJob
{
    string id = 1; // @gotags: bson:"_id,omitempty"

    string name = 8;
    string description = 9;

    ScanInstrument instrument = 10;

    enum ScheduleType
    {
		UNKNOWN = 0; // https://protobuf.dev/programming-guides/dos-donts/ says specify an unknown as 0
        AFTER_IMPORT = 1;
        TIME_BASED = 2;
    }

    ScheduleType scheduleType = 2;

    // Ignored for AFTER_IMPORT type schedules
    //int64 scheduledFirstTimeUnixSec = 3;
    int64 intervalSec = 7;

    // Defines the order of jobs running after import
    int64 jobOrder = 4;

    // What to run?
    JobType jobType = 5;
    map<string, string> jobParameters = 6;
}